#ifndef BB_EXAMPLE_H
#define BB_EXAMPLE_H

/* Some cross-platform definitions generated by autotools */
#if HAVE_CONFIG_H
#  include <config.h>
#endif /* HAVE_CONFIG_H */

#define printf_tm(format, ...) printf("## TM (%s-l%d)[%s()] : " format, __FILE__, __LINE__, __func__ __VA_OPT__(,) __VA_ARGS__);

/*
 * Example function
 */
extern void LibHelloWorld(void);

#endif /* BB_EXAMPLE_H */
