#ifndef YOCTO_TEST_H
#define YOCTO_TEST_H

/* Some cross-platform definitions generated by autotools */
#if HAVE_CONFIG_H
#  include <config.h>
#endif /* HAVE_CONFIG_H */

#define printf_tm(format, ...) printf("\e[1;41m" "## TM (%s-l%d)[%s()]" "\e[0m" " : " format, __FILE__, __LINE__, __func__ __VA_OPT__(,) __VA_ARGS__);

/*
 * Example function
 */
extern void LibHelloWorld(void);

#endif /* YOCTO_TEST_H */
